name: Get all commits

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get all commits
      run: |
        git log --pretty=format:"%h - %an, %ar : %s"
